### ISSUE TITLE
Services could not be load balanced

### ISSUE THREAD

**Issue by mateeyow** [botleg/load-balancing-swarm#1]
So I followed your tutorial word for word, everything worked fine except when I try to launch the load balancer and access it on the public ip on port `80`, it takes a long time to receive a response and when I get the response I get nginx `504 Gateway Time-out`. Here's the output of the `default.conf` of nginx:

```
upstream tutum-nodejs-redis {
    least_conn;

    server 10.0.1.3:32768 max_fails=3 fail_timeout=60 weight=1;
    server 10.0.1.4:32769 max_fails=3 fail_timeout=60 weight=1;
    server 10.0.1.5:32768 max_fails=3 fail_timeout=60 weight=1;
}

server {
    listen 80 default;

    location / {
        proxy_pass http://tutum-nodejs-redis;
    }
}
```

It seems it registered the private ip. `exec` inside the load balancer and installed curl. Tried curling the private ip but it doesn't seem to reach it. I badly need your help. I'm stuck and don't know what is wrong.

**Comment by hanzeljesheen** [comment]
It is supposed to use the private IP. Where are you hosting your Docker Swarm?

**Comment by mateeyow** [comment]
I'm using digital ocean.

**Comment by hanzeljesheen** [comment]
Have you set private networking on with DigitalOcean with `export DIGITALOCEAN_PRIVATE_NETWORKING=true`? I think the private networking is not enabled as you can't access private IPs from inside the load-balancer image.

**Comment by mateeyow** [comment]
It's enabled. Like I told you, I followed your tutorial word for word. I got it working the first try but after trying it again, can't seem to make it work anymore.

**Comment by hanzeljesheen** [comment]
So, it was working at first. Could send the output for `docker-compose ps`.

**Comment by mateeyow** [comment]
Nevermind, it's with the registrator v7.
