### ISSUE TITLE
no servers are inside upstream in /etc/nginx/conf.d/default.conf:6

### ISSUE THREAD

**Issue by lamhaison** [botleg/load-balancing-swarm#2]
I using virtual box to setup docker swarm.
When i run load balacning instance, It do not find any server, and warnning log of nginx (no servers are inside upstream in /etc/nginx/conf.d/default.conf:6). I have a question, how to consult-template have to get docker that I want. In your template have config {{range service $app}}. What is it mean?

**Comment by hanzeljesheen** [comment]
`{{range service $app}}` line is like a loop that pass through all instances of the service `$app`.  Did you try using the docker image [hanzel/load-balancing-swarm](https://hub.docker.com/r/hanzel/load-balancing-swarm/) for load balancer. Just replace the line `build: .` in `docker-compose.yml` with `image: hanzel/load-balancing-swarm` and try it.

**Comment by lamhaison** [comment]
Thanks, Sorry because, on node I do not run registrator on doker engine node. Your tutorial very help. Thanks

**Comment by lamhaison** [comment]
Thanks, Sorry because, on node I do not run registrator on doker engine node. Your tutorial is very help. Thanks

**Comment by lamhaison** [comment]
Thanks, Sorry because, on node I do not run registrator on doker engine node. Your tutorial is very helpful. Thanks

**Comment by lamhaison** [comment]
Thanks, Sorry because, on node I do not run registrator on doker engine node. Your tutorial is very helpful. Thanks
